# Generated by Django 2.2 on 2021-02-20 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='National',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=30, verbose_name='招聘市(区)县')),
                ('company', models.CharField(default='', max_length=30, verbose_name='招聘单位')),
                ('post', models.CharField(default='', max_length=30, verbose_name='招聘岗位')),
                ('code', models.CharField(default='', max_length=20, verbose_name='岗位代码')),
                ('condition', models.TextField(default='', verbose_name='岗位条件')),
                ('number', models.IntegerField(default=0, verbose_name='招聘人数')),
                ('remarks', models.TextField(default='', verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '国编',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(default='', max_length=30, verbose_name='岗位名称')),
                ('code', models.CharField(default='', max_length=20, verbose_name='岗位代码')),
                ('number', models.IntegerField(default=0, verbose_name='招聘人数')),
            ],
            options={
                'verbose_name_plural': '特岗',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=5, verbose_name='姓名')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='电话')),
                ('edit', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('remarks', models.TextField(default='', verbose_name='备注')),
                ('national_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gangwei.National', verbose_name='国编id')),
                ('special_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gangwei.Special', verbose_name='特岗id')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作老师')),
            ],
            options={
                'verbose_name_plural': '学生表',
            },
        ),
    ]
