# Generated by Django 2.2 on 2021-02-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gangwei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score_1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='score_2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='score_3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='score_4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='score_5',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='score_6',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='score_7',
            field=models.FloatField(default=0.0),
        ),
    ]
