# Generated by Django 2.2 on 2021-02-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gangwei', '0002_auto_20210222_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name_plural': '学生表'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='score_6',
        ),
        migrations.RemoveField(
            model_name='student',
            name='score_7',
        ),
    ]
