# Generated by Django 2.2 on 2021-02-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gangwei', '0004_auto_20210223_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='无', max_length=5, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='无', max_length=11, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='student',
            name='remarks',
            field=models.TextField(default='无', verbose_name='备注'),
        ),
    ]
